PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select
?employmentNotation ?SPARQLstring 
where {
    graph <https://raw.githubusercontent.com/PennTURBO/med_mapping/master/tmm_ontology/tmm_ontology.ttl> {
        ?modeledSPARQL a <http://transformunify.org/ontologies/TURBO_0022058> ;
                       <http://purl.org/dc/dcam/domainIncludes> ?employment ;
                       <http://transformunify.org/ontologies/TURBO_0022020> ?SPARQLstring .
        ?employment skos:notation ?employmentNotation
    }
}
